# Generated by Django 4.2.7 on 2023-12-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calgen", "0002_calenderweek_event_week"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CalenderWeek",
            new_name="CalendarWeek",
        ),
        migrations.RemoveField(
            model_name="event",
            name="recurrence",
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
